_name_or_path:
    value: PKU-Alignment/alpaca-7b-reproduced
_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": eval/samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/rewards_help/accuracies
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/grad_norm
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/rewards_safe/accuracies
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss_help
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss_safe
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss_help
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/rewards_safe/accuracies
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/rewards_help/accuracies
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss_safe
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "3":
                - 7
                - 13
                - 23
                - 55
                - 62
                - 66
            "4": 3.10.19
            "5": 0.19.8
            "6": 4.39.3
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.8
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - LlamaForCausalLM
attention_bias:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
begin_suppress_tokens:
    value: null
beta:
    value: 0.5
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 1
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_num_proc:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_dropout:
    value: true
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_steps:
    value: 20
evaluation_strategy:
    value: steps
exponential_decay_length_penalty:
    value: null
f_alpha_divergence_coef:
    value: 1
f_divergence_type:
    value: reverse_kl
finetuning_task:
    value: null
force_use_ref_model:
    value: false
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gamma:
    value: 0
generate_during_eval:
    value: false
gradient_accumulation_steps:
    value: 2
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value:
        use_reentrant: false
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_size:
    value: 4096
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 11008
is_decoder:
    value: false
is_encoder_decoder:
    value: null
jit_mode_eval:
    value: false
label_names:
    value: null
label_pad_token_id:
    value: -100
label_smoothing:
    value: 0
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 0.0005
length_column_name:
    value: length
length_normalization:
    value: false
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /ext_hdd/sjkim/parm/exp/tcheby/runs/Nov26_05-17-11_thor2
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
loss_type:
    value: sigmoid
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 1024
max_position_embeddings:
    value: 2048
max_prompt_length:
    value: 512
max_steps:
    value: -1
max_target_length:
    value: null
metric_for_best_model:
    value: null
min_length:
    value: 0
model_adapter_name:
    value: null
model_init_kwargs:
    value: null
model_type:
    value: llama
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 32
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 32
num_key_value_heads:
    value: 32
num_return_sequences:
    value: 1
num_train_epochs:
    value: 2
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /ext_hdd/sjkim/parm/exp/tcheby
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 32000
padding_value:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 2
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
precompute_ref_log_probs:
    value: false
prediction_loss_only:
    value: false
prefix:
    value: null
pretraining_tp:
    value: 1
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
quantization_config:
    value:
        _load_in_4bit: true
        _load_in_8bit: false
        bnb_4bit_compute_dtype: float32
        bnb_4bit_quant_storage: uint8
        bnb_4bit_quant_type: fp4
        bnb_4bit_use_double_quant: false
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: BITS_AND_BYTES
ray_scope:
    value: last
ref_adapter_name:
    value: null
ref_model_init_kwargs:
    value: null
ref_model_mixup_alpha:
    value: 0.9
ref_model_sync_steps:
    value: 64
reference_free:
    value: false
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value: null
rope_theta:
    value: 10000
rpo_alpha:
    value: null
run_name:
    value: 4r1_4r2_2epoch_0.5p
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 1000
save_strategy:
    value: steps
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
split_batches:
    value: null
suppress_tokens:
    value: null
sync_ref_model:
    value: false
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float16
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.39.3
truncation_mode:
    value: keep_end
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 32001
warmup_ratio:
    value: 0
warmup_steps:
    value: 20
weight_decay:
    value: 0.05
